print('\033[1;31m', '=' * 10, 'Tabuada', '=' * 10, '\033[m')
n = int(input('Digite um número para ver sua tabuada: '))
print('{} X {:2} = {}'.format(n, 1, n * 1))
print('{} X {:2} = {}'.format(n, 2, n * 2))
print('{} X {:2} = {}'.format(n, 3, n * 3))
print('{} X {:2} = {}'.format(n, 4, n * 4))
print('{} X {:2} = {}'.format(n, 5, n * 5))
print('{} X {:2} = {}'.format(n, 6, n * 6))
print('{} X {:2} = {}'.format(n, 7, n * 7))
print('{} X {:2} = {}'.format(n, 8, n * 8))
print('{} X {:2} = {}'.format(n, 9, n * 9))
print('{} X {:2} = {}'.format(n, 10, n * 10))
