v = input('Digite algo para ser analisado: ')
print('É alfabeto?  {}.'.format(v.isalpha()))
print('É numérido?  {}.'.format(v.isnumeric()))
print('É alfanumérico?  {}.'.format(v.isalnum()))
print('Está em maiúscolo?  {}.'.format(v.isupper()))
print('Está em minúsculo? {}.'.format(v.islower()))
print('Está capitalizado? {}.'.format(v.istitle()))
