print('Analisador de nomes')
nome = str(input('Digite seu nome completo: ')).strip()
separa = nome.split()
print('Seu nome em maiúsculo é {}.'.format(nome.upper()))
print('Seu nome em minúsculo é {}.'.format(nome.lower()))
print('Seu nome tem ao todo {} letras.'.format(len(nome) - nome.count(' ')))
print('O seu primeiro nome tem {} letras.'.format(len(separa[0])))
